2025-08-16 20:16:07,696 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:16:07,696 - INFO - composites.py:61 -                                  
2025-08-16 20:16:07,696 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:16:14,018 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:16:14,018 - INFO - composites.py:82 - Processing started
2025-08-16 20:16:14,018 - INFO - composites.py:83 -         Tile: x09_y07
2025-08-16 20:16:14,019 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:16:14,021 - INFO - composites.py:87 -                           
2025-08-16 20:16:14,021 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:16:14,916 - INFO - composites.py:91 -                           
2025-08-16 20:16:14,916 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:16:14,936 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x09_y07/S2L2A_medcomp_x09_y07_202001.odc-metadata.yaml
2025-08-16 20:16:14,936 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:16:14,936 - INFO - composites.py:105 - 
2025-08-16 20:16:14,936 - INFO - composites.py:106 -              !!! SKIPPED: Tile x09_y07 | Time: 2020-01 | In 0.12 minutes
2025-08-16 20:16:14,936 - INFO - composites.py:107 - 
2025-08-16 20:16:15,709 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:16:15,709 - INFO - composites.py:61 -                                  
2025-08-16 20:16:15,709 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:16:21,445 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:16:21,445 - INFO - composites.py:82 - Processing started
2025-08-16 20:16:21,445 - INFO - composites.py:83 -         Tile: x10_y07
2025-08-16 20:16:21,445 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:16:21,445 - INFO - composites.py:87 -                           
2025-08-16 20:16:21,447 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:16:21,476 - INFO - composites.py:91 -                           
2025-08-16 20:16:21,476 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:16:21,492 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x10_y07/S2L2A_medcomp_x10_y07_202001.odc-metadata.yaml
2025-08-16 20:16:21,492 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:16:21,492 - INFO - composites.py:105 - 
2025-08-16 20:16:21,492 - INFO - composites.py:106 -              !!! SKIPPED: Tile x10_y07 | Time: 2020-01 | In 0.1 minutes
2025-08-16 20:16:21,492 - INFO - composites.py:107 - 
2025-08-16 20:16:22,206 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:16:22,206 - INFO - composites.py:61 -                                  
2025-08-16 20:16:22,206 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:16:27,526 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:16:27,526 - INFO - composites.py:82 - Processing started
2025-08-16 20:16:27,526 - INFO - composites.py:83 -         Tile: x09_y08
2025-08-16 20:16:27,526 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:16:27,526 - INFO - composites.py:87 -                           
2025-08-16 20:16:27,526 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:16:27,556 - INFO - composites.py:91 -                           
2025-08-16 20:16:27,556 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:16:27,571 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x09_y08/S2L2A_medcomp_x09_y08_202001.odc-metadata.yaml
2025-08-16 20:16:27,571 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:16:27,571 - INFO - composites.py:105 - 
2025-08-16 20:16:27,571 - INFO - composites.py:106 -              !!! SKIPPED: Tile x09_y08 | Time: 2020-01 | In 0.09 minutes
2025-08-16 20:16:27,571 - INFO - composites.py:107 - 
2025-08-16 20:16:28,302 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:16:28,302 - INFO - composites.py:61 -                                  
2025-08-16 20:16:28,302 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:16:34,119 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:16:34,119 - INFO - composites.py:82 - Processing started
2025-08-16 20:16:34,119 - INFO - composites.py:83 -         Tile: x10_y08
2025-08-16 20:16:34,119 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:16:34,119 - INFO - composites.py:87 -                           
2025-08-16 20:16:34,119 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:16:34,152 - INFO - composites.py:91 -                           
2025-08-16 20:16:34,152 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:16:34,166 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x10_y08/S2L2A_medcomp_x10_y08_202001.odc-metadata.yaml
2025-08-16 20:16:34,166 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:16:34,166 - INFO - composites.py:105 - 
2025-08-16 20:16:34,166 - INFO - composites.py:106 -              !!! SKIPPED: Tile x10_y08 | Time: 2020-01 | In 0.1 minutes
2025-08-16 20:16:34,166 - INFO - composites.py:107 - 
2025-08-16 20:16:34,899 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:16:34,899 - INFO - composites.py:61 -                                  
2025-08-16 20:16:34,899 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:16:40,572 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:16:40,572 - INFO - composites.py:82 - Processing started
2025-08-16 20:16:40,572 - INFO - composites.py:83 -         Tile: x11_y08
2025-08-16 20:16:40,572 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:16:40,572 - INFO - composites.py:87 -                           
2025-08-16 20:16:40,572 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:16:40,604 - INFO - composites.py:91 -                           
2025-08-16 20:16:40,605 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:16:40,620 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x11_y08/S2L2A_medcomp_x11_y08_202001.odc-metadata.yaml
2025-08-16 20:16:40,620 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:16:40,620 - INFO - composites.py:105 - 
2025-08-16 20:16:40,620 - INFO - composites.py:106 -              !!! SKIPPED: Tile x11_y08 | Time: 2020-01 | In 0.1 minutes
2025-08-16 20:16:40,620 - INFO - composites.py:107 - 
2025-08-16 20:16:41,328 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:16:41,329 - INFO - composites.py:61 -                                  
2025-08-16 20:16:41,329 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:16:46,932 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:16:46,932 - INFO - composites.py:82 - Processing started
2025-08-16 20:16:46,932 - INFO - composites.py:83 -         Tile: x09_y09
2025-08-16 20:16:46,932 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:16:46,932 - INFO - composites.py:87 -                           
2025-08-16 20:16:46,932 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:16:46,964 - INFO - composites.py:91 -                           
2025-08-16 20:16:46,964 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:16:46,977 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x09_y09/S2L2A_medcomp_x09_y09_202001.odc-metadata.yaml
2025-08-16 20:16:46,977 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:16:46,977 - INFO - composites.py:105 - 
2025-08-16 20:16:46,977 - INFO - composites.py:106 -              !!! SKIPPED: Tile x09_y09 | Time: 2020-01 | In 0.09 minutes
2025-08-16 20:16:46,977 - INFO - composites.py:107 - 
2025-08-16 20:16:47,715 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:16:47,716 - INFO - composites.py:61 -                                  
2025-08-16 20:16:47,716 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:16:53,399 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:16:53,399 - INFO - composites.py:82 - Processing started
2025-08-16 20:16:53,399 - INFO - composites.py:83 -         Tile: x10_y09
2025-08-16 20:16:53,399 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:16:53,400 - INFO - composites.py:87 -                           
2025-08-16 20:16:53,400 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:16:53,536 - INFO - composites.py:91 -                           
2025-08-16 20:16:53,536 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:16:53,549 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x10_y09/S2L2A_medcomp_x10_y09_202001.odc-metadata.yaml
2025-08-16 20:16:53,549 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:16:53,549 - INFO - composites.py:105 - 
2025-08-16 20:16:53,549 - INFO - composites.py:106 -              !!! SKIPPED: Tile x10_y09 | Time: 2020-01 | In 0.1 minutes
2025-08-16 20:16:53,549 - INFO - composites.py:107 - 
2025-08-16 20:16:54,268 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:16:54,268 - INFO - composites.py:61 -                                  
2025-08-16 20:16:54,268 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:17:00,042 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:17:00,043 - INFO - composites.py:82 - Processing started
2025-08-16 20:17:00,043 - INFO - composites.py:83 -         Tile: x06_y10
2025-08-16 20:17:00,043 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:17:00,043 - INFO - composites.py:87 -                           
2025-08-16 20:17:00,043 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:17:00,078 - INFO - composites.py:91 -                           
2025-08-16 20:17:00,078 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:17:00,096 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x06_y10/S2L2A_medcomp_x06_y10_202001.odc-metadata.yaml
2025-08-16 20:17:00,096 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:17:00,096 - INFO - composites.py:105 - 
2025-08-16 20:17:00,096 - INFO - composites.py:106 -              !!! SKIPPED: Tile x06_y10 | Time: 2020-01 | In 0.1 minutes
2025-08-16 20:17:00,096 - INFO - composites.py:107 - 
2025-08-16 20:17:00,919 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:17:00,919 - INFO - composites.py:61 -                                  
2025-08-16 20:17:00,919 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:17:06,949 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:17:06,949 - INFO - composites.py:82 - Processing started
2025-08-16 20:17:06,949 - INFO - composites.py:83 -         Tile: x08_y10
2025-08-16 20:17:06,950 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:17:06,950 - INFO - composites.py:87 -                           
2025-08-16 20:17:06,950 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:17:06,986 - INFO - composites.py:91 -                           
2025-08-16 20:17:06,986 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:17:07,006 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x08_y10/S2L2A_medcomp_x08_y10_202001.odc-metadata.yaml
2025-08-16 20:17:07,006 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:17:07,006 - INFO - composites.py:105 - 
2025-08-16 20:17:07,006 - INFO - composites.py:106 -              !!! SKIPPED: Tile x08_y10 | Time: 2020-01 | In 0.1 minutes
2025-08-16 20:17:07,006 - INFO - composites.py:107 - 
2025-08-16 20:17:08,164 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:17:08,164 - INFO - composites.py:61 -                                  
2025-08-16 20:17:08,164 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:17:14,298 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:17:14,298 - INFO - composites.py:82 - Processing started
2025-08-16 20:17:14,298 - INFO - composites.py:83 -         Tile: x09_y10
2025-08-16 20:17:14,298 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:17:14,298 - INFO - composites.py:87 -                           
2025-08-16 20:17:14,298 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:17:14,330 - INFO - composites.py:91 -                           
2025-08-16 20:17:14,330 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:17:14,345 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x09_y10/S2L2A_medcomp_x09_y10_202001.odc-metadata.yaml
2025-08-16 20:17:14,345 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:17:14,345 - INFO - composites.py:105 - 
2025-08-16 20:17:14,345 - INFO - composites.py:106 -              !!! SKIPPED: Tile x09_y10 | Time: 2020-01 | In 0.1 minutes
2025-08-16 20:17:14,345 - INFO - composites.py:107 - 
2025-08-16 20:17:15,094 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:17:15,094 - INFO - composites.py:61 -                                  
2025-08-16 20:17:15,094 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:17:20,860 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:17:20,860 - INFO - composites.py:82 - Processing started
2025-08-16 20:17:20,860 - INFO - composites.py:83 -         Tile: x10_y10
2025-08-16 20:17:20,860 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:17:20,860 - INFO - composites.py:87 -                           
2025-08-16 20:17:20,860 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:17:20,893 - INFO - composites.py:91 -                           
2025-08-16 20:17:20,893 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:17:20,905 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x10_y10/S2L2A_medcomp_x10_y10_202001.odc-metadata.yaml
2025-08-16 20:17:20,905 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:17:20,905 - INFO - composites.py:105 - 
2025-08-16 20:17:20,905 - INFO - composites.py:106 -              !!! SKIPPED: Tile x10_y10 | Time: 2020-01 | In 0.1 minutes
2025-08-16 20:17:20,905 - INFO - composites.py:107 - 
2025-08-16 20:17:21,678 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:17:21,678 - INFO - composites.py:61 -                                  
2025-08-16 20:17:21,678 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:17:27,362 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:17:27,362 - INFO - composites.py:82 - Processing started
2025-08-16 20:17:27,362 - INFO - composites.py:83 -         Tile: x11_y10
2025-08-16 20:17:27,362 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:17:27,362 - INFO - composites.py:87 -                           
2025-08-16 20:17:27,362 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:17:27,496 - INFO - composites.py:91 -                           
2025-08-16 20:17:27,498 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:17:27,511 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x11_y10/S2L2A_medcomp_x11_y10_202001.odc-metadata.yaml
2025-08-16 20:17:27,511 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:17:27,511 - INFO - composites.py:105 - 
2025-08-16 20:17:27,511 - INFO - composites.py:106 -              !!! SKIPPED: Tile x11_y10 | Time: 2020-01 | In 0.1 minutes
2025-08-16 20:17:27,511 - INFO - composites.py:107 - 
2025-08-16 20:17:28,312 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:17:28,312 - INFO - composites.py:61 -                                  
2025-08-16 20:17:28,312 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:17:34,198 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:17:34,198 - INFO - composites.py:82 - Processing started
2025-08-16 20:17:34,198 - INFO - composites.py:83 -         Tile: x08_y11
2025-08-16 20:17:34,198 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:17:34,198 - INFO - composites.py:87 -                           
2025-08-16 20:17:34,198 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:17:34,229 - INFO - composites.py:91 -                           
2025-08-16 20:17:34,230 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:17:34,247 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x08_y11/S2L2A_medcomp_x08_y11_202001.odc-metadata.yaml
2025-08-16 20:17:34,247 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:17:34,247 - INFO - composites.py:105 - 
2025-08-16 20:17:34,247 - INFO - composites.py:106 -              !!! SKIPPED: Tile x08_y11 | Time: 2020-01 | In 0.1 minutes
2025-08-16 20:17:34,247 - INFO - composites.py:107 - 
2025-08-16 20:17:34,986 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:17:34,986 - INFO - composites.py:61 -                                  
2025-08-16 20:17:34,986 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:17:40,622 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:17:40,622 - INFO - composites.py:82 - Processing started
2025-08-16 20:17:40,622 - INFO - composites.py:83 -         Tile: x09_y11
2025-08-16 20:17:40,622 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:17:40,622 - INFO - composites.py:87 -                           
2025-08-16 20:17:40,622 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:17:40,654 - INFO - composites.py:91 -                           
2025-08-16 20:17:40,654 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:17:40,672 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x09_y11/S2L2A_medcomp_x09_y11_202001.odc-metadata.yaml
2025-08-16 20:17:40,672 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:17:40,672 - INFO - composites.py:105 - 
2025-08-16 20:17:40,672 - INFO - composites.py:106 -              !!! SKIPPED: Tile x09_y11 | Time: 2020-01 | In 0.09 minutes
2025-08-16 20:17:40,672 - INFO - composites.py:107 - 
2025-08-16 20:17:41,410 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:17:41,410 - INFO - composites.py:61 -                                  
2025-08-16 20:17:41,410 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:17:47,043 - INFO - composites.py:80 - The Dask client listens to http://127.0.0.1:8787/status
2025-08-16 20:17:47,044 - INFO - composites.py:82 - Processing started
2025-08-16 20:17:47,044 - INFO - composites.py:83 -         Tile: x10_y11
2025-08-16 20:17:47,044 - INFO - composites.py:84 -         Time: 2020-01
2025-08-16 20:17:47,044 - INFO - composites.py:87 -                           
2025-08-16 20:17:47,044 - INFO - composites.py:88 - Establishing connection to datacube
2025-08-16 20:17:47,077 - INFO - composites.py:91 -                           
2025-08-16 20:17:47,077 - INFO - composites.py:92 - Sanity test: Check if dataset already exists in the datacube
2025-08-16 20:17:47,092 - WARNING - composites.py:103 - This composite already exists in file://///nas-rs.topo.auth.gr/Latomeia/DROUGHT/COMPOS/2020/01/x10_y11/S2L2A_medcomp_x10_y11_202001.odc-metadata.yaml
2025-08-16 20:17:47,092 - WARNING - composites.py:104 - The composite is skipped. Exit function. Continuing to next.
2025-08-16 20:17:47,092 - INFO - composites.py:105 - 
2025-08-16 20:17:47,092 - INFO - composites.py:106 -              !!! SKIPPED: Tile x10_y11 | Time: 2020-01 | In 0.09 minutes
2025-08-16 20:17:47,093 - INFO - composites.py:107 - 
2025-08-16 20:17:47,822 - INFO - composites.py:59 - #######################################################################
2025-08-16 20:17:47,822 - INFO - composites.py:61 -                                  
2025-08-16 20:17:47,822 - INFO - composites.py:62 - Initializing Dask cluster for parallelization
2025-08-16 20:17:57,878 - ERROR - base_events.py:1826 - Task exception was never retrieved
future: <Task finished name='Task-15527' coro=<ensure_future.<locals>._wrap_awaitable() done, defined at C:\Users\fotakidis\anaconda3\envs\drought\Lib\asyncio\tasks.py:683> exception=RuntimeError('Nanny failed to start.')>
Traceback (most recent call last):
  File "C:\Users\fotakidis\anaconda3\envs\drought\Lib\site-packages\distributed\core.py", line 528, in start
    await wait_for(self.start_unsafe(), timeout=timeout)
  File "C:\Users\fotakidis\anaconda3\envs\drought\Lib\site-packages\distributed\utils.py", line 1923, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\fotakidis\anaconda3\envs\drought\Lib\site-packages\distributed\nanny.py", line 372, in start_unsafe
    raise RuntimeError("Nanny failed to start worker process")
RuntimeError: Nanny failed to start worker process

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\fotakidis\anaconda3\envs\drought\Lib\asyncio\tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
  File "C:\Users\fotakidis\anaconda3\envs\drought\Lib\site-packages\distributed\core.py", line 536, in start
    raise RuntimeError(f"{type(self).__name__} failed to start.") from exc
RuntimeError: Nanny failed to start.
